### ISSUE TITLE
Recording (anonymized) numbers?

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-starter#153]
In a recent reply to a tweet of mine, Pivotal's VP of Product Marketing noted that the numbers of new projects started at `start.pivotal.io` is a better measure of success than the raw number of framework jar downloads.

If we had the (anonymized obviously) numbers for projects started and the table
of features (servers?) selected - it would help us greatly in working out what bits of
MicroProfile people were most using/interested in and what helped move the needle.
(build, measure, learn :-) ).

Clearly we would need to inform people to the fact we recorded these anonymized
numbers for the puposes of making MicroProfile even more awesome to clear
GDPR in the EU (and I guess politeness elsewhere). 

What do we think about recording these usage stats? 

Gordon
```
https://twitter.com/rseroter/status/1127190270599020544
Richard Seroter
VP of Product Marketing at @pivotal, Microsoft MVP, @infoq editor, @pluralsight trainer, blogger, author, speaker
**"No doubt. That's why "projects built at http://start.spring.io " is a better overall metric, as it shows an actual outcome."**
```

**Comment by rdebusscher** [comment]
Hi Gordon,

We do record the following information today
- Number of downloads
- Time, selected runtime, selected MP Version and selected specifications for the examples.

This way, we have an idea of the usage and the "popularity" of the runtimes but do not keep any personal information.

However, I do not agree with the statement
> numbers of new projects started at start.pivotal.io is a better measure of success than the raw number of framework jar downloads.

which indicates that the usage of such a website is mandatory in order to use the framework (which is not a good sign for the ease of use).
On the other hand, I agree that raw downloads don't tell you much since a lot of people are using ephemeral CI environments.

**Comment by aeiras** [comment]
@hutchig this issue is a great follow up to that architecture call where we chatted about tracing MP extensions' usage. 

Lets discuss it on next MP Community hangout.

**Comment by Karm** [comment]
This is already implemented, we have been logging project creation details since day 1.
