### ISSUE TITLE
Add link to REST API to the main web page

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#204]

**Comment by cealsair** [comment]
I like the idea very much. However, I'd like to make this some sort of button or clickable link that clearly indicates to the user that clicking on it will copy the "curl ...." string to their clipboard so that they can paste it in a Terminal window. Also, I'd like to see text label included that clearly tells users what the button is for and how to use it.

**Comment by rdebusscher** [comment]
I think using a link and clipboard as too much overhead for this simple thing.  @rstjames from User Experience point of view, how should this best be presented?

**Comment by cealsair** [comment]
I was referring to adding a COPY symbol next to the "REST API CALL" label. The COPY symbol would look similar to this:
https://play.google.com/store/apps/details?id=nl.robwu.copylink&hl=en_US
The user then could click on the COPY symbol. This action would store the "curl..." cmd in the clipboard. The user could then go to his/her Terminal window and do a paste. This would simplify things and make the user experience easier.
