### ISSUE TITLE
Populate the list of MicroProfile versions when the Server is selected

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-starter#76]
Currently, MicroProfile Server field is disabled until MP version is selected. This forces to first select the version and then runtime. Sometimes a desired runtime doesn't support the selected version and the user has to try several versions until they find their desired runtime.

Proposal:

If version isn't selected, let the Server field enabled and populate it with all the available Servers. Then if a server field is selected, populate the Version field with all MP versions supported by the Server.

In the end, it will be possible to do both:

* select an MP version and then choose from Servers that support it
* select an MP server and choose from Versions that are supported by it

**Comment by kenfinnigan** [comment]
I'm not sure if such a change would be beneficial.

I wouldn't expect users that already have a favorite or preferred runtime to use a generic MP starter to create their project. If a user only ever wants to use Thorntail, for instance, I would expect them to use https://thorntail.io/generator/ instead of the MP starter.

I see the MP starter as catering to those that don't have a runtime preference, or are maybe exploring which runtimes support the latest MP release. For that reason I think the current UI logic is sufficient

**Comment by OndroMih** [comment]
It doesn't necessarily have to be only for newcomers to MicroProfile. I don't like fragmentation and users, (even Thorntail users) don't like it either. Power users know where to go for a thorntail starter, but those who are less power users or work with multiple servers, would find it convenient to use MP starter as a starting point.

This also goes well with my other suggestion, #75, where servers would add more resources about them. I thought about adding a URL to a landing page for the selected server, but there could also be a link to a thorntail starter for thorntail. Then people would easily find Throntail starter and go there if they need something more complex than MicroProfile starter.

**Comment by Karm** [comment]
This is live on https://test-start.microprofile.io/ now.  Pending 0.9.5 release to get promoted to https://start.microprofile.io/ 

Closing the issue.
